name: Tests (Ruby)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *" # 6 A.M.

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.2']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Set up DB
        run: ./bin/rails db:setup
      - name: Test Engine initializers
        run: ./bin/appraisal ruby scripts/initializers_test.rb
      - name: Run tests
        run: ./bin/appraisal rails test
